server.port=${SERVER_PORT:8080}
spring.profiles.active=${APP_PROFILE:test}
# JWT
security.jwt.duration=${JWT_DURATION:86400}

# Password recover
email.password-recover.token.minutes=${TOKEN_MINUTES:30}

security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}
cors.origins=${CORS_ORIGINS:http://localhost:3000}

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:MyID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:MySecret}
cloud.aws.region.static=${AWS_REGION:us-east-1}

# AWS SNS Topics
aws.sns.user-created.topic-arn=${SNS_USER_CREATED_ARN:arn:aws:sns:us-east-1:test}
aws.sns.password-recovery.topic-arn=${SNS_PASSWORD_RECOVERY_ARN:arn:aws:sns:us-east-1:test}
aws.sns.book-available.topic-arn=${SNS_BOOK_AVAILABLE_ARN:arn:aws:sns:us-east-1:test}

# AWS S3
aws.s3.bucket-name=${S3_BUCKET_NAME:biblioteca-imagens-prod}

# URL base usada para recuperacao de senha
email.password-recover.uri=${RECOVER_URI:http://localhost:8080/reset-password?token=}
